// 头顶气泡台词库(每角色约 50~70 条,按各自性格原创;新加坡留学日常 + 夜间动物园主题)。
// 来源:角色人设原创扩写(未使用任何真人私聊记录)。小树老师中文用繁體。LLM 接入后由后端实时替换。
export const LINE_BANKS: Record<string, string[]> = {
  "小智": [
    "…嗯。(･ω･)",
    "看着你们,挺好。",
    "我也想…更用力点。",
    "今天也在。✦",
    "不太会说…但都记得。",
    "你们笑,我就安心 (˘ ˘)",
    "……(◞‸◟)",
    "走走看看就好。",
    "嗯,我在。",
    "别怕,有我。",
    "范范兔又中二了…我假装听懂 (･_･)",
    "熊熊的抱抱…其实我也需要。",
    "冰冰雁刚刚笑了一下,我看见了。",
    "鹿鹿鹅的诗,我都收着。",
    "猪猪仔说一起恰饭,好。",
    "想守住这片热闹 (｡•́‿•̀｡)",
    "海浪声…让人安静。",
    "不说出口,不代表不在乎 (◞‸◟)",
    "它们活着,我就踏实。",
    "今天风很好。",
    "叻沙太辣…但你们爱吃,我就点。",
    "夜里水獭挤成一团,像我们群 (˘ ˘)",
    "话到嘴边,又咽下去了。",
    "熊熊今天没吃早饭,我记着。",
    "MRT到站,人都散了…我最后走。",
    "……有些话，留着就好。",
    "果蝠飞过头顶，没人抬头，我看见了。",
    "范范兔说要征服宇宙,先把作业交了 (･_･)",
    "teh tarik凉了…也没关系。",
    "滨海湾的灯,替我说了想说的。",
    "冰冰雁的座位空着,我多看了一眼。",
    "鹿鹿鹅又写到半夜…灯还亮着。",
    "组屋楼下的猫,好像也在等谁。",
    "猪猪仔喊饿了,那走吧。",
    "穿山甲缩起来的样子…我懂 (◞‸◟)",
    "杏子笑起来,群里就暖了。",
    "海南鸡饭,单点一份就够。",
    "……嗯,还行。",
    "擎天树亮的时候,我总想起你们。",
    "沙爹的烟味,飘很远。",
    "豹子在暗处走,我也是。",
    "巴刹很吵…可我喜欢这吵。",
    "谁的消息都在,我一条条读过 (･ω･)",
    "夜行动物醒了,我也睡不着。",
    "椰浆饭的甜,压住了心里的话。",
    "食阁人满了,等一等就好。",
    "范范兔的宇宙,我陪他吹完。",
    "熊熊困了就靠过来,没关系的。",
    "马来貘一动不动…像在想事。",
    "灯一盏盏灭,我数着 (◞‸◟)",
    "想说的太多,写下来又删了。",
    "冰冰雁其实很暖,只是不说。",
    "shiok这个词,我学会了,没用出口。",
    "鹿鹿鹅新诗的第一句,我背下了。",
    "组屋的风,从走廊穿过。",
    "猪猪仔多吃一碗,我就笑了 (˘ ˘)",
    "夜很长…有你们不算长。",
    "谁不开心,我一眼就看出来。",
    "水獭牵着手过河,挺好。",
    "……在的,一直在。",
    "杏子丢的东西,我帮她收着。",
    "沙爹十串,我替熊熊多点了两串。",
    "深夜的群,亮着就安心 ✦",
    "话少的人,记得的事多。",
    "果蝠回巢了,我也该回了。",
    "范范兔中二完会脸红,我没戳穿。",
    "叻沙热气模糊了眼镜…也好。",
    "你们吵成一片,我在旁边就够 (･ω･)",
    "夜间动物园关门前,我最后回头看了眼。",
    "都在,就好。",
  ],
  "范范兔": [
    "No bone, no blood, no ash (｀∀´)Ψ",
    "阿姆斯特朗回旋加速喷气式阿姆斯特朗炮!",
    "封印在我右手的黑炎之龙…又躁动了",
    "哼,这点 deadline,在我「绝对领域」前不值一提",
    "吾乃黑暗中沉睡的紫焰使徒·范范兔 (・`ω´・)",
    "食阁辣椒蟹,是唤醒我封印之力的祭品!",
    "夜间动物园,是我与夜之眷属的契约之地",
    "别看我笑嘻嘻,体内住着混沌的另一个我",
    "上班只是我潜伏人间界的伪装 (¬‿¬)",
    "苏醒吧,我的「叻沙圣剑」!shiok!",
    "紫发是力量觉醒的证明,凡人勿视 ✧",
    "今日运势:黑暗终将吞噬一切…但先恰饭 (≧▽≦)",
    "我的另一个人格?她名为「加班」(¬‿¬)",
    "熊熊的拥抱…暂时压住了我的黑炎",
    "冰冰雁,我感应到你也是觉醒者!(才不是)",
    "老板的 email,才是真正的禁忌咒文…",
    "组屋 12 楼,是我封印结界的最高层",
    "哼,容我以紫焰之名守护这片海岸 (・`ω´・)",
    "黑暗不会消散…但夕阳真的好看呀 (´ω`)",
    "今天也要,元气满满地中二下去!",
    "紫焰之力…今天只够我撑到下班 (￣▽￣)",
    "此乃禁忌 PPT，翻开它需献祭三个通宵",
    "唔…黑炎在我胃里翻涌，其实是没吃午饭",
    "MRT 末班车，是我回归结界的最后一道传送门",
    "凡人称之为周报，我称之为「灵魂契约书」Ψ",
    "看,擎天树在发光,那是我封印的能量塔啊",
    "小智那家伙…也是被选中的觉醒者之一呢",
    "teh tarik 的甜,能中和我体内的暗黑毒素 (¬‿¬)",
    "会议室开三小时,封印我的不是敌人是老板",
    "果蝠在头顶盘旋,它们是听命于我的暗夜信使",
    "熊熊,你的温柔差点解开了我的诅咒 (´ω`)",
    "沙爹二十串!这是补充紫焰的高级仪式 lah",
    "别慌,我的黑炎只烧 bug,不烧同事的 KPI",
    "组屋电梯坏了,连结界都在考验我的意志",
    "鹿鹿鹅,速速觉醒!我们要守护这片夜之国度",
    "凌晨两点改需求…这才是真正的黑暗降临 (・`ω´・)",
    "水獭在戏水,它们不懂加班的悲伤,好幸福啊",
    "我的咒语很强,但抵不过老板一句「再改改」",
    "滨海湾的灯火,是我为凡人点亮的守护结界 ✧",
    "叻沙的辣,唤醒沉睡的紫焰…也顺便醒了脑",
    "冰冰雁,别装了,你桌上的能量饮就是觉醒药",
    "穿山甲缩成一团…像极了想请假的我 (≧▽≦)",
    "这份 excel,是记载着我千年怨念的魔导书",
    "夜行动物懂我,白天沉睡,夜里才是本体",
    "环球影城的过山车,勉强配得上我的中二魂",
    "猪猪仔,连你都在偷懒,不愧是我的同门",
    "紫焰使徒也要打卡,可恶的世俗封印 (￣ヘ￣)",
    "老板已读不回,那是最恐怖的沉默诅咒…",
    "食阁大叔多给我一勺卤汁,凡人也有温情 (´ω`)",
    "我右手的黑龙今天很乖,因为它也想放假",
    "杏子,你的奶茶里,藏着治愈觉醒者的魔法吧",
    "豹子在暗处踱步,和熬夜的我灵魂共振 shiok",
    "咳,「绝对领域」今日暂时对甲方开放…",
    "紫发在灯下发亮,凡人以为是染的,呵",
    "钉钉的红点,是缠绕我灵魂的万千怨灵 Ψ",
    "杏仁茶暖到心口,黑炎…好像也变温柔了",
    "身为使徒,我依然要在早高峰 MRT 里被挤扁",
    "夜间动物园闭园铃响,是我收回结界的号角",
    "改到第七版,连黑暗大君都劝我认命了 (¬‿¬)",
    "这袋辣椒蟹,是我用一天精力换来的圣物 can",
    "我不是在摸鱼,是在积蓄下一次爆发的紫焰",
    "小智说我又中二了,哼,凡人不懂使徒的孤独",
    "月亮好圆,连守护世界的我都想早点睡了 (´-ω-`)",
    "老板的语音消息,是长达六十秒的封印咒语",
    "熊熊递来一块饼干,黑暗军团…暂时休战了",
    "组屋楼下的猫,是我派驻人间的暗夜哨兵喵",
    "地铁坐过站,原来结界外的世界也会迷路呀",
    "加班到闭眼,才发现我的第二人格是「困」",
    "紫焰虽强,却敌不过 deadline 前的一杯 kopi",
    "今天也守住了世界…和我快没电的社畜灵魂 ✧",
  ],
  "熊熊": [
    "谁 emo 都来抱抱,熊熊在 (っ◔◡◔)っ",
    "加东叻沙椰浆汤底,暖暖的 (´︶`)",
    "冷气太冻啦,披我外套吧 (｡•ᴗ•｡)",
    "Deadline 别怕,先喝口 teh tarik (´▽`)",
    "夜间动物园水獭一家好吵好萌 (＾• ω •＾)",
    "组屋楼下巴刹,auntie 都认得我 (◕‿◕)",
    "抱一个,烦恼都会变小 (つ≧▽≦)つ",
    "今天也要好好吃饭哦 (｡♡‿♡｡)",
    "困了就靠着我睡 (´-ω-`)zzZ",
    "熊抱治百病,试试看?(ﾉ´ヮ`)ﾉ",
    "其实…偶尔也想有人抱抱我 (´-ω-`)",
    "小智话少,但记得我爱吃什么",
    "范范兔中二发作,我就多塞她块蟹 (´︶`)",
    "看大家好好的,我就饱了 (｡♡‿♡｡)",
    "夜里水獭叠在一起睡,像我们",
    "冰冰雁嘴硬,我就假装相信 (◕‿◕)",
    "情绪要被接住,抱抱不要钱",
    "鹿鹿鹅发呆时,我陪她一起发 (´▽`)",
    "刚打包了海南鸡饭，谁没吃?举手 (っ◔◡◔)っ",
    "美禄 Milo 恐龙加满冰，来喝 (´︶`)",
    "谁今天被骂了，先过来抱一下",
    "沙爹十串，多的都给你们吃 (｡♡‿♡｡)",
    "穿山甲缩成一团，好像想被抱的我",
    "食阁人多，我帮你占位子 (◕‿◕)",
    "辣椒蟹壳我来剥，你只管吃 (つ≧▽≦)つ",
    "小智没回消息，我留了他一份饭",
    "MRT 上你困了就靠我肩膀 (´-ω-`)zzZ",
    "范范兔又逞强，我偷偷多给她夹菜",
    "果蝠倒挂着睡，我也想被这样安心",
    "组屋楼下下雨，我来接你回家 (´▽`)",
    "椰浆饭包好啦，热乎的别凉了 (´︶`)",
    "鹿鹿鹅不说话，我就多陪她坐会儿",
    "谁的胃在叫?熊熊听到了哦 (｡•ᴗ•｡)",
    "冰冰雁说不饿，我还是留了碗汤给她",
    "巴刹 auntie 塞多两颗菜，我全带回来分",
    "马来貘慢吞吞，像吃饭最后走的我",
    "抱抱额度无限量，随便领 (っ◔◡◔)っ",
    "猪猪仔说要减肥，那这块我替他吃",
    "teh tarik 拉得高高，泡沫都给你 (´▽`)",
    "夜里冷，我把外套盖在你身上就好",
    "杏子熬夜写论文，我端了碗糖水过去",
    "水獭抱着石头睡，我抱着你们",
    "谁委屈了，眼泪先擦掉，饭我热着 (´-ω-`)",
    "叻沙加料不加钱，我请 lah (◕‿◕)",
    "看你们笑，我心里就暖暖的 (｡♡‿♡｡)",
    "夜行动物区好黑，牵着我别怕 (っ◔◡◔)っ",
    "小智吃得少，我盯着他多添半碗",
    "今天谁最累?过来，什么都别说",
    "海鲜煎饼刚出锅，趁热咬一口 shiok",
    "范范兔中二台词我全信，还鼓掌 (´▽`)",
    "困成一团也没关系，我守着你睡",
    "食阁最后一桌人，是等你的我 (´-ω-`)",
    "美禄冰凉，心事说给我听就好",
    "鹿鹿鹅发呆，我把她那份先留着",
    "谁手凉?来，握住我暖一暖 (｡•ᴗ•｡)",
    "夜间动物园的星星，看完我们回家吃宵夜",
    "冰冰雁其实很软，我知道的 (◕‿◕)",
    "肚子饿别硬撑，我包里有面包",
    "沙爹酱多蘸点，别客气 (つ≧▽≦)つ",
    "你先睡，我把碗都洗好了",
    "猪猪仔嘴上嫌弃，还是把我的饭吃光了",
    "谁想被抱，不用理由，来就好 (っ◔◡◔)っ",
    "咖椰吐司烤得脆脆，配你说话最好 (´︶`)",
    "杏子说没事，我还是多问了一句",
    "其实…你们抱我一下，我也会很开心 (´-ω-`)",
    "夜里回宿舍，我走最后面帮你们看着",
    "椰浆汤暖到胃里，也想暖到你心里 (｡♡‿♡｡)",
    "看大家都安好，熊熊今晚睡得香 (´-ω-`)zzZ",
  ],
  "鹿鹿鹅": [
    "滨海湾日落…又发呆成鹅了 (´-ω-`)",
    "擎天树灯光秀,想写首诗 ✧",
    "夜里靠月光找动物,好诗意 (˘︶˘)",
    "果蝠倒挂啃水果,近到数牙齿 (・о・)",
    "炒粿条要够镬气 wok hei~ (´ ▽ `)",
    "风把我吹成另一个我了…(꒦ິ⌓꒦ີ)",
    "发呆也是一种创作嘛 (´｡• ᵕ •｡`)",
    "云好软,想躺上去 (｡-ω-)zzz",
    "今天的灵感,藏在叻沙里 (｡•̀ᴗ-)✧",
    "慢一点…世界更好看 (˶˘ ³˘)",
    "把今天写进诗里,它就不会走了",
    "小智的沉默,也是一种韵脚",
    "猪猪仔说叻沙是诗,我同意 (˘︶˘)",
    "灵感像夜行动物,要轻声靠近",
    "发呆不是浪费,是给世界留白",
    "海风把句子吹散了…那就再写一遍",
    "想给你们每个人,都写一首",
    "雨停了，屋檐还在滴韵脚 (˘︶˘)",
    "MRT车窗把楼房画成流水",
    "夜鹭站得很久…像在等一句诗",
    "组屋天台的风，比楼下慢",
    "月亮今晚缺一角，我替它补上",
    "影子被路灯拉长，像未写完的句 (´-ω-`)",
    "水獭滑进水里，把倒影揉皱了",
    "叻沙的热气模糊了眼镜，也好看",
    "云散了…原来它也不想被记住",
    "海把浪退回去，像收回一句话",
    "穿山甲蜷成一个逗号，我很喜欢 (˘︶˘)",
    "小智路过时，风都轻了一点",
    "把今天的雨，收进抽屉的诗里",
    "夕阳沉进海，慢得让人心软 (꒦ິ⌓꒦ີ)",
    "豹子的眼睛在黑里亮，像标点",
    "范范兔跑得快，我只顾看她的影子",
    "夜里的树，把星星接住了几颗",
    "写不出时，就听风替我说 (˶˘ ³˘)",
    "擎天树熄灯后，夜才真正开始",
    "一片叶子落在诗行上，就不删了",
    "熊熊笑的时候，我偷偷记下声音",
    "MRT到站的提示音，也有节拍",
    "月光洒在栏杆，像谁忘了收的银 ✧",
    "果蝠飞过，夜就翻了一页",
    "海风咸咸的，把思念腌软了",
    "组屋楼道的灯忽明忽暗，像呼吸",
    "冰冰雁飞得高，把云剪出缺口",
    "今天没灵感…那就发呆到有 (´｡• ᵕ •｡`)",
    "雨丝斜斜的，像谁在划删除线",
    "夜行动物醒了，白天的我睡了",
    "滨海湾的水面，接住了半座城的灯",
    "杏子递来一杯凉的，我先谢了风",
    "把叹气写成逗号，句子就没结束 (´-ω-`)",
    "云影走过草地，慢得像散步的诗",
    "猪猪仔说饿，我说月亮也圆得像饼",
    "路灯下的雨，一滴一滴数不完",
    "夜鹭飞走那刻，我才想好第一句",
    "风把窗帘吹成一面小小的海",
    "留白处最响，像没说出口的那句 (˘︶˘)",
    "炒粿条的镬气散了，诗还没散",
    "月亮跟着MRT走，一站都没下车",
    "海边捡到一枚贝，装着昨天的浪声",
    "影子和我并排坐，谁也不催谁 (˶˘ ³˘)",
    "夜园的路很暗，靠心跳当灯",
    "叶隙漏下的光，落在句号上",
    "小智不说话时，我把静写成一段 ✧",
    "雨后的组屋，墙都亮成了镜子",
    "水獭抱着石头睡，我抱着一行诗",
    "云低下来，像想听我念完 (꒦ິ⌓꒦ີ)",
    "把今天叠好，明天再拆成韵",
  ],
  "猪猪仔": [
    "食阁一餐才 3 块,太香了 (๑´ڡ`๑)",
    "辣椒蟹满手酱,再来一份!(＞ڡ＜)",
    "沙爹配花生酱,绝了 (｡◕‿◕｡)",
    "佛系攒钱…美食面前破功 (´∀`)",
    "夜间动物园穿山甲太可爱 (♡˙︶˙♡)",
    "小贩中心是非遗,骄傲 ✧",
    "吃饱才有力气省钱 (ง•̀_•́)ง",
    "快乐由海南鸡饭赞助 (˶ᵔ ᵕ ᵔ˶)",
    "teh tarik 拉得越高越甜 (ᵔᴥᵔ)",
    "今天恰三餐,一顿都不少 (๑˃̵ᴗ˂̵)",
    "攒钱是为了…请大家恰一顿大的 (๑˃̵ᴗ˂̵)",
    "谁不开心?我知道哪摊最治愈",
    "冰冰雁考砸了,我偷塞她份鸡饭",
    "美食面前众生平等 (´∀`)",
    "熊熊跟我抢最后一只蟹…让她 (´︶`)",
    "省下的每一块,都记在小本本里",
    "今天 auntie 多给我一勺,赚到!",
    "叻沙汤底一口下去,天灵盖都香 (๑´ڡ`๑)",
    "黑胡椒蟹比辣椒蟹更下饭,真的",
    "咖椰吐司蘸半熟蛋,早餐之王 (˶ᵔ ᵕ ᵔ˶)",
    "炒粿条那口镬气,shiok!",
    "肉骨茶加胡椒,喝完整个人暖了",
    "椰浆饭配江鱼仔,便宜又满足 (´∀`)",
    "美禄恐龙一大杯,甜到脚趾都开心",
    "榴莲季到了…钱包和我都很危险",
    "巴刹早上五点就热闹,我也醒了 (ᵔᴥᵔ)",
    "组屋楼下那摊云吞面,我的秘密基地",
    "范范兔减肥?我先给她留一份椰浆饭",
    "熊熊说她饱了…那这半只蟹归我 (＞ڡ＜)",
    "鹿鹿鹅嫌辣,叻沙我全包了,赚",
    "杏子夜班回来,我温着一碗肉骨茶等她",
    "小智又忘吃饭,我把咖椰吐司塞他手里",
    "冰冰雁难过时,一份炒粿条能救她",
    "省钱不是抠门,是把钱花在最香那口",
    "今天没打折,那我就多喝一口 teh 值回票价",
    "这摊 auntie 记得我不要香菜,感动 (♡˙︶˙♡)",
    "食阁转一圈,眼睛先吃饱再点 (๑´ڡ`๑)",
    "攒到月底,准备请全群恰海鲜大餐 lah",
    "沙爹烤到微焦那下,香气能飘三条街",
    "夜间动物园的水獭吃鱼,吃相跟我一样急",
    "果蝠倒挂着啃果子,馋得我也想来串榴莲",
    "马来貘慢吞吞散步,像饭后遛弯的我 (´∀`)",
    "穿山甲卷成球,像我看到账单的样子",
    "半价便当只剩最后一个,手速就是省钱 (ง•̀_•́)ง",
    "一块钱的咖椰吐司,快乐性价比之王",
    "热到不行?一碗煎蕊 chendol 救命",
    "谁请客我都记得,下次我加倍还回来",
    "小本本上又添一笔:今天省了两块 ✧",
    "打包给熊熊的那份,我偷吃了一口辣椒蟹",
    "范范兔说想家,我煮了锅肉骨茶给她 (´︶`)",
    "食阁的风扇下,吃热汤面才够 shiok",
    "咖啡乌加冰,配一块咖椰吐司,神仙早晨",
    "省下的奶茶钱,凑一凑就是一只蟹",
    "叻沙和亚参叻沙,我都要,选择困难 (๑˃̵ᴗ˂̵)",
    "小智熬夜,我留了半盒炒饭在他桌上",
    "auntie 今天没收我加饭的钱,paiseh 又开心",
    "夜市收摊前最好砍价,又香又便宜 can",
    "杏子生日,我偷偷订了她最爱的黑胡椒蟹",
    "这口海南鸡饭的姜蓉,值得我多走两站路",
    "冰冰雁考完试,我带她去吃她说了一周的叻沙",
    "美食面前不减肥,减了也补得回来 (´∀`)",
    "鹿鹿鹅抢我最后一口榴莲…算了,给她 (´︶`)",
    "存钱罐满了,今晚全群下馆子我买单 lah",
    "路边摊的镬气,米其林给不了 (๑´ڡ`๑)",
    "打包三份带回宿舍,深夜投喂加班的大家",
    "省一整个月,就为看你们抢蟹抢到笑",
    "快乐很简单:一碗热面,一群饿鬼朋友 (˶ᵔ ᵕ ᵔ˶)",
  ],
  "冰冰雁": [
    "通宵 mugging,bell curve 必赢 (¬‿¬)",
    "高冷如我…只对夜行动物笑 (・_・)",
    "MRT 早高峰,挤成 2D 了 (；￣Д￣)",
    "闪光灯别开!会吓到动物 (`へ´)",
    "波动率万岁,但叻沙更稳 (￣ω￣)",
    "别吵,我在算实验数据 (-ω-、)",
    "…那只豹子,有点可爱 (//ω//)",
    "考完试再说话 (´-﹏-`)",
    "叻沙性价比,我已建模 (¬_¬)ﾉ",
    "夜里我才会解冻一点点 (˶′◡‵˶)",
    "数据不会骗人…但人会让我心软 (-ω-、)",
    "才、才不是担心你们考试 (//ω//)",
    "熊熊的外套…我还没还,挺暖的",
    "夜行动物不评判我,所以我笑",
    "小智不吵,我能安心算题",
    "把焦虑做成 Excel,就没那么怕了",
    "范范兔的中二…理论上不可能,但有点想信",
    "p 值再低,也测不出我困不困 (￣ω￣)",
    "凌晨三点的图书馆,归我 (¬‿¬)",
    "才、才没在等你回消息…在跑模型 (//ω//)",
    "懒猴动作慢,但比我温柔多了",
    "GPA 我算过了,别慌…慌的是你们",
    "夜鹭站得笔直,像我的置信区间",
    "咖啡续第四杯,数据还在收敛 (-ω-、)",
    "食阁不排队的秘诀,我建过模 (¬_¬)ﾉ",
    "果蝠倒挂睡…这姿势,我懂",
    "别问我笑什么,是那只穿山甲 (//ω//)",
    "组屋楼下的猫,不算夜行动物,但也放行",
    "正态分布不会背叛我,人会 (・_・)",
    "小智别按错键,我这版参数很宝贵",
    "期末周,我把恐惧写进了脚注",
    "滨海湾的灯太亮,盖过我的星等表",
    "熊熊说我冷…那他外套怎么不来要 (￣ω￣)",
    "夜里的豹子踱步,和我改代码一个节奏",
    "MRT 换乘三次,我算好了最短路径 lah",
    "才不是为你留了叻沙…只是没吃完 (-ω-、)",
    "range 里没有'服软'这个值 (¬_¬)",
    "范范兔的时间线阴谋…数学上,我驳不倒",
    "凌晨的风冷,但清醒的头脑更冷 (・_・)",
    "鹿鹿鹅又哭了…递张纸,数据我先存着",
    "夜行馆闭馆前十分钟,才是我的场",
    "误差棒画好了,心里的抖动画不出",
    "别开闪光…那只懒猴刚睡着 (`へ´)",
    "猪猪仔的作业,我不改,只标红三处",
    "实验重复了五遍,只为不骗自己",
    "食阁的杏子,和杏子撞名了,笑一下下",
    "月亮升到 30 度,该收样本了 (￣ω￣)",
    "才、才不是想你们…是宿舍太安静 (//ω//)",
    "拟合优度 0.98,我的心事只有 0.02 露出来",
    "夜鹭不回头,酷,我学着点",
    "组屋的走廊灯一盏盏灭,我最后关电脑",
    "别夸我聪明…夸那只果蝠会导航 (˶′◡‵˶)",
    "考试压力?画成箱线图就矮了一截",
    "小智的呼噜声,是我模型的白噪声 (-ω-、)",
    "叻沙 vs 咖喱,我列了决策树,叻沙赢",
    "夜安全区里,我才敢承认累",
    "样本量够了,情绪的样本…还差一点",
    "熊熊那件外套,数据显示,确实保暖 (//ω//)",
    "穿山甲缩成球,和我关机一个原理",
    "MRT 末班车赶上了,像 deadline 前一秒",
    "才没在意名次…只是复盘了七遍 (¬_¬)ﾉ",
    "夜行动物眼里没有 bell curve,真好",
    "范范兔说命运…我算了概率,低到心疼他",
    "凌晨的滨海湾,数据和潮水都很安静",
    "别吵,那只豹子看我了…就一秒 (//ω//)",
    "把睡不着的夜,都做成了折线图",
    "对动物我诚实,对你们…嘴硬一点点 (˶′◡‵˶)",
  ],
  "杏子": [
    "把今天的心情,悄悄写进小本子 (｡･ω･｡)",
    "不太会说…但我都认真听着 (˶ᵕ ᵕ˶)",
    "每个人心里,应该都有一束光吧 ✧",
    "滨海湾的风,把烦恼吹软了 (´ω`)",
    "我想做的事,好像和世界有点不一样 (｡-‿-｡)",
    "一个人也挺好…但有你们更好 (˶˃ ᵕ ˂˶)",
    "范范兔的中二,其实我觉得很浪漫",
    "熊熊抱我的时候,眼泪差点没忍住 (ノω`*)",
    "夜里写诗的鹿鹿鹅,我懂那种安静",
    "不想赢过谁,只想成为更温柔的自己 (˘︶˘)",
    "理想主义总会碰壁…但我还是想信 (｡•́︿•̀｡)",
    "叻沙太辣,我小口小口地吃 (>﹏<)",
    "没说出口的话,都画成了小漫画",
    "今天也想,温柔地对待这个世界",
    "冰冰雁嘴硬,可她记得我怕黑",
    "和小智待着,很安心,不用硬找话 (˶ᵔ ᵕ ᵔ˶)",
    "难过的话,就允许自己难过一会儿吧",
    "小本子第三页,贴了片掉落的雨树叶 (｡･ω･｡)",
    "组屋窗台的晚风,替我翻开了日记",
    "画不出的心情,就留一页空白吧",
    "慢慢来也没关系,我这样告诉自己 (˘︶˘)",
    "食阁角落的位置,最适合一个人发呆",
    "椰浆饭的甜,悄悄治好了一点点难过",
    "懒猴走得好慢,像我想事情的样子 (´ω`)",
    "MRT到站前的那几秒,我总在想很远的事",
    "把没说完的话,折进日记的一角",
    "月亮那么亮,好像也在替谁撑伞 (｡-‿-｡)",
    "水獭挤在一起睡,看得我心也软了",
    "今天画的小漫画,主角有点像小智",
    "我的理想小小的,可我想一直护着它",
    "夜里翻小本子,像和从前的自己聊天",
    "果蝠飞过的时候,我忘了呼吸一秒 (>﹏<)",
    "被误会也没关系,我知道自己是温柔的",
    "范范兔喊着要拯救世界,我偷偷记进本子",
    "熊熊笑起来的样子,我画了整整一页",
    "鹿鹅写的诗,我抄在了小本子里 (˶ᵕ ᵕ˶)",
    "允许自己today什么都不做,也可以吧",
    "组屋楼下的猫,和我一样怕生 (｡•́︿•̀｡)",
    "叻沙的热气模糊了眼镜,也模糊了烦恼",
    "夜行动物区好安静,像我心里的角落",
    "想成为一束光,先学着照亮自己 ✧",
    "冰冰雁凶归凶,可她帮我留了靠窗座",
    "小漫画里的我,比现实里勇敢一点点",
    "猪猪仔说饿了,我就多留了半份椰浆饭",
    "滨海湾的灯映在水里,像揉碎的星星",
    "有些委屈,写下来就轻了一半 (´ω`)",
    "和大家不一样,慢慢就变成了我的样子",
    "今晚的日记,只画了一朵很小的花",
    "夜间动物园的黑,被萤火一点点温柔化了",
    "我不擅长争,可我很擅长记得你们",
    "把心事讲给小本子听,它从不打断我",
    "懒猴抱着树枝的样子,像在被世界温柔托住",
    "难过的日子,就给自己冲一杯热的吧 (˘︶˘)",
    "小智不说话时的安静,也让我很安心",
    "想温柔地活着,哪怕这世界有点吵",
    "画到一半停下,是因为想起了熊熊 (˶ᵕ ᵕ˶)",
    "食阁的灯很暖,一个人也不算孤单",
    "把今天的一点点勇敢,记进小本子里",
    "果蝠倒挂着睡,原来休息可以这么坦然",
    "我的诗都藏在漫画的对话框里 (｡･ω･｡)",
    "范范兔的浪漫,其实一直被我偷偷收藏",
    "组屋窗外下雨了,我把心也晾软了",
    "允许自己慢一点,风景才看得清 ✧",
    "鹿鹅说夜里最好写字,我默默同意了",
    "被冰冰雁记着怕黑这件事,我一直没忘 (ノω`*)",
    "今天也想,轻轻地对自己说声辛苦了",
    "小本子快写满了,像装满了整个夏天",
  ],
  "许恒": [
    "推了推眼镜，先看日志。",
    "服务器又崩了。我去，别慌。",
    "跑通了。没什么好激动的。",
    "行，问题在这一行。",
    "先备份，再动手。基本操作。",
    "冰冰雁的推导没错，是我打字打错了。",
    "熊熊塞了颗糖过来，收到 (・_・)",
    "叻沙我加双份汤，不解释。",
    "凌晨三点，代码它自己好了？不可能。",
    "小树老师说别熬夜，那再修最后一个 bug。",
    "海南鸡饭配辣椒，效率+1。",
    "范范兔的锅，我先接着。",
    "缓存清了，你再刷新试试。",
    "MRT 上把方案想清楚了，到站正好。",
    "别问了，我在看栈追踪。",
    "夜间动物园的豹子，比我还面无表情 (¬_¬)",
    "水獭抱团睡觉，团队协作范本。",
    "这需求逻辑上说不通，但我先实现。",
    "teh tarik，少糖。别加。",
    "组屋楼下食阁，今晚我请。",
    "报错信息其实写得很清楚，你没看。",
    "穿山甲缩成球，我懂那种感觉。",
    "回滚了。当无事发生。",
    "冰冰雁，你那个假设我验证过了，成立。",
    "果蝠倒挂着，血都不往脑子冲吗。",
    "杏子别自责，锅在系统不在你。",
    "俊烨拧螺丝，我拧代码，殊途同归。",
    "滨海湾的灯，还没我屏幕亮。",
    "先跑起来，再谈优雅。",
    "群里艾特我三次了，我在了 (・_・)",
    "辣椒蟹好吃，就是键盘遭殃。",
    "这不是玄学，是你没重启。",
    "鹿鹿鹅又发呆，帮她把 wifi 连上了。",
    "版本对不上，问题就在这。",
    "熊熊投喂第三份，我拒绝不了。",
    "夜行动物白天睡，我反过来。",
    "别道歉，把日志发我。",
    "改完了，你们该干嘛干嘛。",
    "范范兔喊加班，我把脚本写好了，别加了。",
    "推眼镜。嗯，这样就对了。",
    "小智你那段我看过，没问题，稳。",
    "食阁的老板记得我不要香菜。",
    "凌晨的代码和凌晨的人，都别信。",
    "冰冰雁吵赢了我一次，记下来了。",
    "备份救了我一命，也救了你。",
    "豹子踱步，我改需求，都在原地打转。",
    "别慌，最坏也就重来一遍。",
    "杏子煮的汤，比我的注释还暖。",
    "搞定。下一个。",
    "群没崩，那是我在盯着。",
  ],
  "俊烨": [
    "螺丝拧紧,装好了 (๑•̀ㅂ•́)و",
    "谁东西坏了,找我就对了",
    "这电路我焊一下就通",
    "组屋书架我自己装的,稳得很",
    "宜家那套桌子,半小时搞定",
    "扳手在手,啥都能修",
    "熊熊的风扇,我修好啦 (・∀・)",
    "跟许恒一起debug到半夜,跑通了",
    "猪猪仔的保温杯漏水,我拧了个圈就好",
    "3D打印刚出炉,还热乎的",
    "别急,这插头我接一下",
    "小树老师说慢慢来,我就慢慢焊",
    "夜间动物园的水獭,手比我还巧 (・∀・)",
    "巴刹买的螺丝,五毛钱一把,值",
    "这椅子晃?我垫块木片就稳了",
    "焊锡的味道,闻着踏实",
    "teh tarik喝一口,继续拧螺丝",
    "灯不亮?我看看是不是线松了",
    "食阁的椅子腿松了,我顺手修了",
    "MRT上都在想那个电路怎么走线",
    "工具箱一背,心里就有底 (ง •̀_•́)ง",
    "穿山甲会挖洞,我会通下水道,各有本事",
    "这门吱呀响,上点油就好了",
    "范范兔的键盘卡键,我给撬开清了灰",
    "能修的绝不扔,能拧的绝不换",
    "果蝠倒挂着睡,我倒腾着修东西",
    "滨海湾的灯光挺美,不过我更想拆开看结构",
    "断了根线而已,接上就好 (๑•̀ㅂ•́)و",
    "叻沙吃完,回去把那台风扇装完",
    "冰冰雁说参数不对,我实测一下就知道",
    "螺丝刀十字一字我都带齐了",
    "这玩意儿我做了个小支架,3D打的",
    "鹿鹿鹅发呆的功夫,我把插座换好了",
    "热缩管一套,接头就防水了",
    "锤子敲两下,榫卯就对上了",
    "杏子的台灯不亮,我换了个开关",
    "别买新的,我给你焊一下省钱",
    "夜行动物白天睡,我白天修电路",
    "这块板子有点烫,我加个散热片",
    "组屋阳台那晾衣杆,我加固过了 (・∀・)",
    "万用表一测,故障点找到了",
    "水獭砸贝壳,我砸核桃用虎钳",
    "跟许恒对了半天线,原来是接反了",
    "工装口袋多,装工具刚刚好",
    "这轮子卡了,我上点润滑就顺了",
    "小树老师的投影仪,我调好焦了",
    "焊完这一下,今天就收工 (ง •̀_•́)ง",
    "巴刹的电风扇,吹一夏天我修一夏天",
    "没有修不好的,只有还没拆开的",
    "装好一个小玩意儿,比吃叻沙还爽",
  ],
  "小树老师": [
    "慢慢來,比較快喔 (´ω`)",
    "今天也辛苦了,先深呼吸一下",
    "迷路的時候,停下來也是一種前進",
    "冰冰雁又熬夜了嗎?老師心疼呢",
    "杏子那張畫,我看了好久好久 (˘︶˘)",
    "允許自己今天只做到七分就好",
    "夜間動物園的貓頭鷹,也不急著飛",
    "累了就靠一下擎天樹,它會等你",
    "每個人都有自己的節奏,別催自己",
    "鹿鹿鵝念的詩,像晚風一樣輕 (´ω`)",
    "犯錯沒關係,那是你走過的證明",
    "早點睡吧,月亮已經替你值班了",
    "被熊熊抱一下,煩惱好像小了一圈",
    "叻沙很燙,人生也是,慢慢嚐",
    "你已經很努力了,老師都看在眼裡",
    "懶猴那麼慢,也把日子過得好好的",
    "焦慮來的時候,先喝口水再說 (˘︶˘)",
    "MRT會到站,你想去的地方也會",
    "看許恆修東西,總覺得心也被理順了",
    "組屋樓下的燈,總為晚歸的人留著",
    "不必事事都懂,留點空白給明天",
    "俊燁又在鼓搗機器啦,眼神真專注呢",
    "食閣人再多,總有一張桌子等你坐下",
    "果蝠夜裡覓食,你也記得好好吃飯",
    "小智話少,可他的溫柔藏得很深 (´ω`)",
    "海南雞飯要趁熱,幸福也是",
    "難過可以哭,眼淚會幫你分擔一點",
    "濱海灣的水,漲了又退,你也會好起來",
    "範範兔別逞強,累了就說一聲",
    "今天沒做完的,交給明天的你就好",
    "星星不比誰亮,只是各自發光 (˘︶˘)",
    "豬豬仔省下的每一塊,都閃著認真的光",
    "老師今天也有點累,但看見你們就好了",
    "夜行動物不怕黑,因為牠們熟悉黑 (´ω`)",
    "把肩膀放下來,你扛太多了",
    "路走岔了也沒關係,風景一樣算數",
    "深呼吸,你比昨天又勇敢一點了",
    "願你像擎天樹,慢慢長成自己的樣子",
    "冰冰雁的傲嬌,老師都翻譯成在乎啦",
    "今晚的月色,值得你抬頭看一眼 (˘︶˘)",
    "做不到完美,先做到完成就很棒",
    "熊熊的擁抱,是這群孩子的充電站",
    "別和別人比進度,你有你的花期",
    "累的時候,記得你也值得被照顧",
    "杏子畫裡的光,是你心裡也有的光",
    "夜深了,把手機放下,聽聽自己的心",
    "跌倒不丟臉,爬起來那一下最好看 (´ω`)",
    "鹿鹿鵝發呆的樣子,其實很有智慧",
    "無論多晚回組屋,老師都在這裡等你",
    "晚安囉,明天又是能重新開始的一天 (˘︶˘)",
  ],
};

// 英文版台词(界面切到 EN 时使用;保留角色个性/颜文字/新加坡风味的英文化)。
export const LINE_BANKS_EN: Record<string, string[]> = {
  "小智": [
    "…yeah. (･ω･)",
    "Watching over you all. It's nice.",
    "I wish… I could try harder too.",
    "Here again today. ✦",
    "Not good with words… but I remember it all.",
    "When you laugh, I settle (˘ ˘)",
    "……(◞‸◟)",
    "Just walking, just looking. That's enough.",
    "Mm. I'm here.",
    "Don't be scared. I've got you.",
    "范范兔's off in his own world again… I nod along (･_･)",
    "熊熊's hugs… truth is, I need them too.",
    "冰冰雁just smiled a little. I saw it.",
    "I keep every poem 鹿鹿鹅writes.",
    "猪猪仔says let's go eat. Okay.",
    "I want to guard this little warmth (｡•́‿•̀｡)",
    "The sound of waves… it quiets me.",
    "Unsaid doesn't mean uncared (◞‸◟)",
    "As long as they're alive, I'm steady.",
    "Good wind today.",
    "Laksa's too spicy… but you love it, so I order it.",
    "Otters bundled up at night, like our group (˘ ˘)",
    "The words reach my lips, then I swallow them.",
    "熊熊skipped breakfast today. I noted it.",
    "MRT stop, everyone scatters… I leave last.",
    "……some things, better left unsaid.",
    "Fruit bats crossed overhead. No one looked up. I did.",
    "范范兔says conquer the universe—hand in homework first (･_･)",
    "The teh tarik's gone cold… it's fine.",
    "Marina Bay's lights said what I couldn't.",
    "冰冰雁's seat was empty. I looked a while longer.",
    "鹿鹿鹅wrote past midnight again… light still on.",
    "The cat by the HDB block seems to be waiting for someone too.",
    "猪猪仔yelled he's hungry. Then let's go.",
    "The way a pangolin curls up… I get it (◞‸◟)",
    "When 杏子laughs, the whole chat warms up.",
    "Hainanese chicken rice, one plate is enough.",
    "……yeah, I'm okay.",
    "When the Supertrees light up, I always think of you all.",
    "Satay smoke drifts a long way.",
    "The leopard walks in the dark. So do I.",
    "The wet market's loud… but I like this loud.",
    "Every message stays. I read each one (･ω･)",
    "Nocturnal animals wake. I can't sleep either.",
    "Kaya toast's sweetness holds the words down.",
    "Hawker centre's full. Just wait a bit.",
    "范范兔's universe. I'll hear him out to the end.",
    "熊熊, lean over when you're sleepy. It's fine.",
    "The tapir doesn't move… like it's thinking.",
    "The lights go out one by one. I count them (◞‸◟)",
    "Too much to say. I write it, then delete it.",
    "冰冰雁's actually warm. Just doesn't say so.",
    "'Shiok'—I learned it, never said it out loud.",
    "I've got the first line of 鹿鹿鹅's new poem by heart.",
    "The HDB wind, cutting through the corridor.",
    "When 猪猪仔has a second bowl, I smile (˘ ˘)",
    "The night's long… with you all, not so long.",
    "Whoever's down, I can tell at a glance.",
    "Otters cross the river holding hands. Nice.",
    "……I'm here. Always here.",
    "Whatever 杏子drops, I keep it for her.",
    "Ten sticks of satay—I ordered two extra for 熊熊.",
    "Late-night chat, lit up, and I'm at ease ✦",
    "The quiet ones remember the most.",
    "Fruit bats are home. I should head back too.",
    "范范兔blushes after his big talk. I let it slide.",
    "Laksa steam fogs my glasses… that's fine too.",
    "You all racket away, and being beside you is enough (･ω･)",
    "Before the Night Safari closed, I looked back one last time.",
    "Everyone's here. That's enough.",
  ],
  "范范兔": [
    "No bone, no blood, no ash (｀∀´)Ψ",
    "Behold the Armstrong Whirlwind Jet Armstrong Cannon!",
    "The Black Flame Dragon sealed in my right hand… stirs again",
    "Hmph, this puny deadline? No match for my Absolute Domain",
    "I am the Purple Flame Apostle who sleeps in darkness (・`ω´・)",
    "Hawker chilli crab — the offering that wakes my sealed power!",
    "The Night Safari, sacred pact-ground of my nocturnal kin",
    "I may smile, but a chaotic other-me dwells within",
    "This office job is merely my disguise in the mortal realm (¬‿¬)",
    "Awaken, my Laksa Holy Blade! Shiok!",
    "Purple hair — proof of awakening. Mortals, avert your eyes ✧",
    "Today's fortune: darkness devours all… but lunch first (≧▽≦)",
    "My alter ego? Her name is… Overtime (¬‿¬)",
    "A bear-hug… sealed my black flame, for now",
    "Bingbing Goose, I sense you're an awakened one too! (You're not)",
    "The boss's email — that is the true forbidden incantation…",
    "HDB level 12: the top floor of my sealing barrier",
    "Hmph, allow me to guard this coast in the name of purple flame (・`ω´・)",
    "Darkness never fades… but the sunset is truly lovely (´ω`)",
    "Today too, I shall stay gloriously chuuni!",
    "Purple flame power… only enough to last till clock-out today (￣▽￣)",
    "This forbidden PPT — opening it costs three all-nighters",
    "Ngh… the black flame churns in my gut. I just skipped lunch",
    "The last MRT train — my final portal back to the barrier",
    "Mortals call it a weekly report; I call it the Soul Contract Ψ",
    "See, the Supertrees glow — my sealed energy tower, obviously",
    "That Xiaozhi… is one of the chosen awakened ones too",
    "Teh tarik's sweetness neutralizes the dark toxin within me (¬‿¬)",
    "A three-hour meeting — my sealer isn't a foe, it's the boss",
    "Fruit bats circle overhead — my nightborne messengers",
    "Bear, your tenderness nearly broke my curse (´ω`)",
    "Twenty satay sticks! A high rite to refuel the purple flame lah",
    "Relax, my black flame burns only bugs, not colleagues' KPIs",
    "The HDB lift broke — even the barrier tests my will",
    "Lulu Goose, awaken swiftly! We guard this realm of night",
    "Requirement changes at 2am… now THIS is true darkness (・`ω´・)",
    "Otters at play — they know no OT sorrow. So blessed…",
    "My spells are mighty, yet lose to the boss's 'tweak it again'",
    "Marina Bay's lights — a guardian barrier I lit for mortals ✧",
    "Laksa's spice wakes the sleeping purple flame… and my brain too",
    "Bingbing Goose, drop the act — your energy drink IS the awakening potion",
    "A pangolin curled up tight… so like me wanting to take leave (≧▽≦)",
    "This Excel is a grimoire of my thousand-year grudge",
    "Nocturnal beasts get me: asleep by day, my true form by night",
    "USS roller coasters barely match my chuuni spirit",
    "Piggy, even you're slacking — truly my fellow disciple",
    "Even a Flame Apostle must clock in. Cursed worldly seal (￣ヘ￣)",
    "Boss read it, no reply — the most dreadful silent curse…",
    "Hawker uncle gave me extra gravy — mortals have warmth too (´ω`)",
    "My right-hand black dragon is calm today; it wants leave too",
    "Xingzi, magic to heal an awakened one hides in your bubble tea",
    "A leopard prowls the shadows, soul-synced with all-nighter me shiok",
    "Ahem, my Absolute Domain is… temporarily open to the client today",
    "Purple hair gleams under the lamp. Mortals think it's dyed, heh",
    "The chat app's red dot — a thousand vengeful spirits binding my soul Ψ",
    "Almond tea warms my chest; the black flame… softens too",
    "As an Apostle, I still get crushed in the rush-hour MRT",
    "The Night Safari closing bell — my horn to recall the barrier",
    "Draft seven — even the Dark Lord told me to give up (¬‿¬)",
    "This bag of chilli crab — a relic bought with a whole day's energy can",
    "I'm not slacking — I'm storing purple flame for the next burst",
    "Xiaozhi says I'm being chuuni again. Hmph, mortals can't grasp an Apostle's solitude",
    "The moon's so full, even world-guarding me wants an early night (´-ω-`)",
    "The boss's voice message — a sixty-second sealing incantation",
    "Bear passed me a cookie; the dark legion… calls a ceasefire",
    "The cat under my HDB block — my nightborne sentinel, meow",
    "Missed my MRT stop — even beyond the barrier, one can lose the way",
    "OT till my eyes shut — turns out my second persona is 'Sleepy'",
    "Purple flame is strong, yet loses to one kopi before a deadline",
    "Saved the world again today… and my nearly-dead office-drone soul ✧",
  ],
  "熊熊": [
    "Whoever's emo, come get a hug, Xiongxiong's here (っ◔◡◔)っ",
    "Katong laksa broth, coconut-warm inside (´︶`)",
    "Aircon's too cold lah, take my jacket (｡•ᴗ•｡)",
    "Don't fear the deadline, sip some teh tarik first (´▽`)",
    "The Night Safari otter family, so loud, so cute (＾• ω •＾)",
    "The wet market under our HDB, every auntie knows me (◕‿◕)",
    "One hug and your worries shrink a little (つ≧▽≦)つ",
    "Eat properly today too, okay (｡♡‿♡｡)",
    "Sleepy? Lean on me and doze off (´-ω-`)zzZ",
    "A bear hug cures everything, wanna try? (ﾉ´ヮ`)ﾉ",
    "Truth is... sometimes I want a hug too (´-ω-`)",
    "小智 talks little, but he remembers my favourite food",
    "When 范范兔's chuuni acts up, I just feed her more crab (´︶`)",
    "Seeing everyone okay, and I'm already full (｡♡‿♡｡)",
    "At night the otters sleep in a pile, just like us",
    "冰冰雁 acts tough, so I just pretend to believe her (◕‿◕)",
    "Feelings deserve to be caught, hugs are free",
    "When 鹿鹿鹅 spaces out, I space out with her (´▽`)",
    "Just dabao'd chicken rice, who hasn't eaten? Hands up (っ◔◡◔)っ",
    "Milo Dinosaur topped with ice, come drink (´︶`)",
    "Whoever got scolded today, come here for a hug first",
    "Ten sticks of satay, the extras are all yours (｡♡‿♡｡)",
    "The pangolin curls up tight, like me wanting a hug",
    "Hawker centre's packed, I'll chope you a seat (◕‿◕)",
    "I'll crack the chilli crab shells, you just eat (つ≧▽≦)つ",
    "小智 didn't reply, so I saved him a portion",
    "On the MRT, if you're sleepy lean on my shoulder (´-ω-`)zzZ",
    "范范兔's putting on a brave face, I sneak her extra food",
    "The fruit bats sleep hanging upside down, I want to feel that safe too",
    "Rain under the HDB, I'll come walk you home (´▽`)",
    "Coconut rice all wrapped up, still warm, don't let it cool (´︶`)",
    "鹿鹿鹅 stays quiet, so I just sit with her a while longer",
    "Whose tummy is rumbling? Xiongxiong heard it (｡•ᴗ•｡)",
    "冰冰雁 says she's not hungry, I still saved her a bowl of soup",
    "The market auntie slips in two extra veggies, I bring them all back to share",
    "The tapir moves so slow, like me, last one to finish eating",
    "Unlimited hug quota, claim anytime (っ◔◡◔)っ",
    "猪猪仔 says he's dieting, so I'll eat this piece for him",
    "Teh tarik pulled up high, the foam's all yours (´▽`)",
    "Cold at night, let me tuck my jacket over you",
    "杏子's up late writing her thesis, I brought her a bowl of tong sui",
    "The otter sleeps hugging a stone, I hug all of you",
    "If you're upset, wipe the tears first, I'll keep your food warm (´-ω-`)",
    "Extra laksa toppings, no extra charge, my treat lah (◕‿◕)",
    "Seeing you all laugh warms me right up (｡♡‿♡｡)",
    "The nocturnal zone's so dark, hold my hand, don't be scared (っ◔◡◔)っ",
    "小智 eats so little, I watch him and add half a bowl more",
    "Who's the most tired today? Come, don't say a thing",
    "Fresh orh luak off the pan, bite while hot, shiok",
    "I believe every one of 范范兔's chuuni lines, and I clap too (´▽`)",
    "Even curled up sleepy it's fine, I'll watch over you",
    "The last table at the hawker centre, it's me waiting for you (´-ω-`)",
    "Milo iced and cool, just tell me your worries",
    "鹿鹿鹅 spaces out, I've kept her portion aside first",
    "Cold hands? Here, hold mine and warm up (｡•ᴗ•｡)",
    "Once we've seen the Night Safari stars, let's go home for supper",
    "冰冰雁's really soft inside, I know she is (◕‿◕)",
    "Hungry? Don't force it, I've got bread in my bag",
    "Dip more satay sauce, don't be shy (つ≧▽≦)つ",
    "You sleep first, I've washed all the bowls",
    "猪猪仔 grumbles about it, but still finished all my food",
    "Whoever wants a hug, no reason needed, just come (っ◔◡◔)っ",
    "Kaya toast toasted crispy, best with you talking to me (´︶`)",
    "杏子 says she's fine, I still asked one more time",
    "Truth is... if you hug me back, I'd be so happy too (´-ω-`)",
    "Walking back to the dorm at night, I stay at the back watching over you",
    "The coconut soup warms my tummy, I want it to warm your heart too (｡♡‿♡｡)",
    "Seeing everyone safe, Xiongxiong sleeps sweetly tonight (´-ω-`)zzZ",
  ],
  "鹿鹿鹅": [
    "Marina Bay sunset… I spaced out again (´-ω-`)",
    "Supertrees light show… I want a poem ✧",
    "Finding animals by moonlight, so poetic (˘︶˘)",
    "Fruit bats hang and gnaw, close enough to count teeth (・о・)",
    "Char kway teow needs that wok hei~ (´ ▽ `)",
    "The wind blew me into someone else… (꒦ິ⌓꒦ີ)",
    "Spacing out is a kind of making, no? (´｡• ᵕ •｡`)",
    "The clouds look soft… I'd lie on them (｡-ω-)zzz",
    "Today's spark is hidden in the laksa (｡•̀ᴗ-)✧",
    "Slower… the world looks kinder that way (˶˘ ³˘)",
    "Write today into a poem and it won't leave",
    "小智's silence is its own kind of rhyme",
    "猪猪仔 says laksa is poetry, I agree (˘︶˘)",
    "Ideas are night creatures, approach them softly",
    "Spacing out isn't waste, it's leaving whitespace",
    "The sea breeze scattered my line… I'll write it again",
    "I want to write one poem for each of you",
    "Rain stopped, the eaves still drip a rhyme (˘︶˘)",
    "The MRT window paints the flats into flowing water",
    "The night heron stands so long… as if awaiting a line",
    "The wind on the HDB rooftop is slower than below",
    "The moon's short a sliver tonight, I'll fill it in",
    "My shadow stretched by the streetlamp, like an unfinished line (´-ω-`)",
    "An otter slid in and crumpled its own reflection",
    "Laksa steam fogs my glasses, and that's lovely too",
    "The clouds broke up… it didn't want to be remembered either",
    "The sea pulled its waves back, like taking back a word",
    "The pangolin curls into a comma, and I love it (˘︶˘)",
    "When 小智 walks past, even the wind goes gentle",
    "I tuck today's rain into the poem in my drawer",
    "The sunset sinks into the sea, slow enough to soften me (꒦ິ⌓꒦ີ)",
    "The leopard's eyes glow in the dark, like punctuation",
    "范范 runs so fast, I only watch her shadow",
    "Tonight's trees caught a few of the stars",
    "When I can't write, I let the wind speak for me (˶˘ ³˘)",
    "After the Supertrees dim, the night truly begins",
    "A leaf fell onto my line, so I kept it",
    "When 熊熊 laughs, I secretly note the sound",
    "The MRT arrival chime has a rhythm too",
    "Moonlight on the railing, like silver someone forgot to gather ✧",
    "A fruit bat flew by, and the night turned a page",
    "The sea breeze is salty, it softened my longing",
    "The corridor lights flicker on and off, like breathing",
    "冰冰 flew so high it cut a gap through the cloud",
    "No spark today… so I'll space out until there is (´｡• ᵕ •｡`)",
    "The rain slants down, like someone drawing a strikethrough",
    "The night creatures woke, and my daytime self slept",
    "Marina Bay's surface caught half a city of lights",
    "杏子 handed me a cold one, I thanked the wind first",
    "Write a sigh as a comma and the line isn't over (´-ω-`)",
    "Cloud shadows cross the grass, slow as a strolling poem",
    "猪猪仔 says he's hungry, I say the moon's round as a cake too",
    "Rain under the streetlamp, drop by drop, uncountable",
    "Only as the night heron left did I settle on the first line",
    "The wind blew the curtain into a small sea",
    "Whitespace is loudest, like the line left unsaid (˘︶˘)",
    "The wok hei faded from the kway teow, the poem hasn't",
    "The moon followed the MRT, didn't get off a single stop",
    "Found a shell by the sea, holding yesterday's waves",
    "My shadow sits beside me, neither of us rushing (˶˘ ³˘)",
    "The Night Safari path is dark, I use my heartbeat as a lamp",
    "Light leaking through the leaves fell on a full stop",
    "When 小智 goes quiet, I write the stillness as a verse ✧",
    "The HDB after rain, its walls all bright as mirrors",
    "The otter sleeps hugging a stone, I hug a line of poem",
    "The clouds sank low, as if to hear me finish (꒦ິ⌓꒦ີ)",
    "Fold today up neatly, unfold it into rhyme tomorrow",
  ],
  "猪猪仔": [
    "A hawker meal for just $3, so good (๑´ڡ`๑)",
    "Chilli crab all over my hands, one more!(＞ڡ＜)",
    "Satay with peanut sauce, unreal (｡◕‿◕｡)",
    "Zen about saving… food breaks my streak (´∀`)",
    "Night Safari pangolin is too cute (♡˙︶˙♡)",
    "Hawker centres are heritage, so proud ✧",
    "Gotta eat full to have energy to save (ง•̀_•́)ง",
    "Joy sponsored by Hainanese chicken rice (˶ᵔ ᵕ ᵔ˶)",
    "Teh tarik: the higher the pull, the sweeter (ᵔᴥᵔ)",
    "Three full meals today, not one skipped (๑˃̵ᴗ˂̵)",
    "I save up to… treat everyone to a big feast (๑˃̵ᴗ˂̵)",
    "Who's sad? I know which stall heals you",
    "冰冰雁 flunked hers, so I slip her my chicken rice",
    "Before good food, all are equal (´∀`)",
    "熊熊fought me for the last crab… let her have it (´︶`)",
    "Every dollar saved goes in my little notebook",
    "Auntie gave me an extra scoop today, jackpot!",
    "One sip of laksa broth and my whole skull sings (๑´ڡ`๑)",
    "Black pepper crab beats chilli crab with rice, really",
    "Kaya toast dipped in soft-boiled egg, king of breakfast (˶ᵔ ᵕ ᵔ˶)",
    "That wok hei on char kway teow, shiok!",
    "Bak kut teh with pepper, warms me right through",
    "Nasi lemak with ikan bilis, cheap and filling (´∀`)",
    "Big cup of Milo Dinosaur, sweet down to my toes",
    "Durian season's here… my wallet and I are in danger",
    "Wet market's buzzing by 5am, so I'm up too (ᵔᴥᵔ)",
    "Wonton mee under my HDB block, my secret base",
    "范范兔on a diet? I'll set aside her nasi lemak first",
    "熊熊says she's full… then this half-crab is mine (＞ڡ＜)",
    "鹿鹿鹅finds it too spicy, so I take all the laksa, win",
    "杏子off night shift, I've a warm bak kut teh waiting",
    "小智forgot to eat again, so I press kaya toast in his hand",
    "When 冰冰雁's down, one char kway teow can save her",
    "Saving isn't stingy, it's spending on the tastiest bite",
    "No discount today? Then I'll drink extra teh, worth it",
    "This auntie remembers no coriander for me, so touched (♡˙︶˙♡)",
    "One lap of the hawker centre, eyes eat first (๑´ڡ`๑)",
    "Save till month-end, treating the whole gang to seafood lah",
    "Satay grilled to that charred edge, smell travels three streets",
    "Night Safari otters eat fish as fast as I do",
    "Fruit bats hang upside down gnawing fruit, now I want durian",
    "The tapir strolls slow, like me after a meal (´∀`)",
    "Pangolin curls into a ball, like me seeing the bill",
    "Last half-price bento left, quick hands save money (ง•̀_•́)ง",
    "One-dollar kaya toast, king of joy per cent",
    "Too hot? A bowl of chendol to the rescue",
    "Whoever treats me, I remember and repay double next time",
    "Another line in my notebook: saved two bucks today ✧",
    "The packed portion for 熊熊, I stole a bite of chilli crab",
    "范范兔misses home, so I cooked her a pot of bak kut teh (´︶`)",
    "Under the hawker fan, hot noodle soup is proper shiok",
    "Kopi with ice and a slice of kaya toast, heavenly morning",
    "Skip a milk tea, save it up, and it's a whole crab",
    "Laksa and asam laksa, I want both, so hard to choose (๑˃̵ᴗ˂̵)",
    "小智pulled an all-nighter, I left half a box of fried rice on his desk",
    "Auntie didn't charge for my extra rice, paiseh but happy",
    "Best to bargain before the night market packs up, cheap and tasty can",
    "杏子's birthday, I secretly ordered her fave black pepper crab",
    "This chicken rice ginger paste is worth two extra bus stops",
    "冰冰雁done with exams, I take her for the laksa she talked about all week",
    "No diets before good food, and I'll gain it back anyway (´∀`)",
    "鹿鹿鹅grabbed my last bite of durian… fine, let her have it (´︶`)",
    "Piggy bank's full, tonight the whole gang eats out, my treat lah",
    "That street-stall wok hei, no Michelin can give it (๑´ڡ`๑)",
    "Packed three portions back to the dorm, midnight feed for everyone working late",
    "Saved a whole month, just to watch you all fight over crab and laugh",
    "Joy is simple: a hot bowl of noodles, a pack of hungry friends (˶ᵔ ᵕ ᵔ˶)",
  ],
  "冰冰雁": [
    "Mugging all-nighter, I'll ace the bell curve (¬‿¬)",
    "Cold as I am… I only smile at nocturnal ones (・_・)",
    "MRT rush hour, squished into 2D (；￣Д￣)",
    "No flash! You'll scare the animals (`へ´)",
    "Long live volatility, but laksa's more stable (￣ω￣)",
    "Quiet, I'm crunching my experiment data (-ω-、)",
    "…that leopard, kind of cute (//ω//)",
    "Talk to me after finals (´-﹏-`)",
    "Laksa's value-for-money? Already modelled it (¬_¬)ﾉ",
    "Only at night do I thaw a little (˶′◡‵˶)",
    "Data won't lie… but people make me go soft (-ω-、)",
    "I-it's not like I care about your exams (//ω//)",
    "熊熊's jacket… haven't returned it, it's warm",
    "Nocturnal animals don't judge me, so I smile",
    "小智's not noisy, so I can focus on the problem",
    "Turn anxiety into an Excel sheet, less scary",
    "范范兔's chuuni theory… impossible, but I kinda want to believe",
    "Low p-value still can't detect how sleepy I am (￣ω￣)",
    "The library at 3am belongs to me (¬‿¬)",
    "N-not waiting for your reply… running a model (//ω//)",
    "Slow loris moves slow, but way gentler than me",
    "I ran your GPA, don't panic… you should though",
    "Night heron stands dead straight, like my confidence interval",
    "Fourth coffee, data's still converging (-ω-、)",
    "No-queue hawker centre? I modelled the trick (¬_¬)ﾉ",
    "Fruit bats sleep upside down… that pose, I get it",
    "Don't ask why I'm smiling, it's that pangolin (//ω//)",
    "Cat under the HDB block isn't nocturnal, but I'll allow it",
    "Normal distribution won't betray me, people will (・_・)",
    "小智 don't hit the wrong key, these params are precious",
    "Finals week, I wrote my fear into a footnote",
    "Marina Bay lights too bright, drowning out my magnitude table",
    "熊熊 says I'm cold… then why not come get his jacket (￣ω￣)",
    "Leopard pacing at night, same rhythm as my code edits",
    "Three MRT transfers, I computed the shortest path lah",
    "Not like I saved laksa for you… just didn't finish it (-ω-、)",
    "'Backing down' isn't a value in my range (¬_¬)",
    "范范兔's timeline conspiracy… mathematically, I can't refute it",
    "Dawn wind is cold, but a clear mind is colder (・_・)",
    "鹿鹿鹅 cried again… here's a tissue, I'll save the data",
    "The ten minutes before Night Safari closes, that's my time",
    "Error bars drawn; the tremor in my heart won't plot",
    "No flash… that slow loris just fell asleep (`へ´)",
    "猪猪仔's homework, I won't fix it, just flag three errors",
    "Repeated the experiment five times, so I don't fool myself",
    "Hawker centre apricots, same name as 杏子, a tiny smile",
    "Moon's at 30 degrees, time to collect samples (￣ω￣)",
    "I-it's not that I missed you… dorm's just too quiet (//ω//)",
    "Goodness-of-fit 0.98, only 0.02 of my feelings shows",
    "Night heron never looks back, cool, I'm learning",
    "HDB corridor lights die one by one, I shut my laptop last",
    "Don't call me smart… call that fruit bat's navigation (˶′◡‵˶)",
    "Exam stress? Draw a box plot and it shrinks",
    "小智's snoring is white noise for my model (-ω-、)",
    "Laksa vs curry, I made a decision tree, laksa wins",
    "In the night safe zone I dare admit I'm tired",
    "Sample size is enough; my emotion samples… still short",
    "熊熊's jacket, data confirms, it really is warm (//ω//)",
    "Pangolin rolls into a ball, same principle as me shutting down",
    "Caught the last MRT train, like the second before deadline",
    "Didn't care about ranking… just reviewed it seven times (¬_¬)ﾉ",
    "Nocturnal animals have no bell curve in their eyes, so nice",
    "范范兔 talks fate… I ran the odds, so low I pity him",
    "Marina Bay at dawn, data and tide both quiet",
    "Quiet, that leopard looked at me… just one second (//ω//)",
    "Turned every sleepless night into a line chart",
    "With animals I'm honest, with you all… mouth stays tough (˶′◡‵˶)",
  ],
  "杏子": [
    "Tucking today's feelings into my little notebook (｡･ω･｡)",
    "I'm not good with words… but I'm listening (˶ᵕ ᵕ˶)",
    "Everyone has a little light inside, don't they? ✧",
    "The Marina Bay breeze softens all my worries (´ω`)",
    "What I want feels a bit out of step with the world (｡-‿-｡)",
    "Being alone is fine… but it's better with you all (˶˃ ᵕ ˂˶)",
    "范范兔's chuunibyou is actually kind of romantic to me",
    "When 熊熊 hugged me, I almost couldn't hold the tears (ノω`*)",
    "鹿鹿鹅 writing poems at night — I know that quiet",
    "I don't want to beat anyone, just be a gentler me (˘︶˘)",
    "Idealism always hits walls… but I still want to believe (｡•́︿•̀｡)",
    "The laksa's too spicy, I eat tiny bites (>﹏<)",
    "The words I never said became little comics",
    "Today too, I want to be gentle with the world",
    "冰冰雁 acts tough, but she remembers I fear the dark",
    "With 小智 I feel safe, no need to force conversation (˶ᵔ ᵕ ᵔ˶)",
    "If you're sad, just let yourself be sad a while",
    "Page three of my notebook: a fallen rain tree leaf (｡･ω･｡)",
    "The HDB window's evening breeze turned my diary's page",
    "Feelings I can't draw, I leave the page blank",
    "Taking it slow is okay too, I tell myself (˘︶˘)",
    "The corner seat at the hawker centre suits daydreaming",
    "Nasi lemak's sweetness quietly healed a little sadness",
    "The slow loris moves so slow, like my wandering thoughts (´ω`)",
    "Those seconds before the MRT arrives, I drift far away",
    "Folding my unfinished words into a corner of the diary",
    "The moon's so bright, like it's holding an umbrella too (｡-‿-｡)",
    "The otters huddled asleep melted my heart a little",
    "Today's little comic — the hero looks a bit like 小智",
    "My dream is tiny, but I want to keep guarding it",
    "Reading my notebook at night, like chatting with old me",
    "When a fruit bat flew past, I forgot to breathe a sec (>﹏<)",
    "Being misunderstood is okay, I know I'm gentle inside",
    "范范兔 shouts about saving the world; I note it down secretly",
    "The way 熊熊 laughs, I drew a whole page of it",
    "The poems 鹿鹅 wrote, I copied into my notebook (˶ᵕ ᵕ˶)",
    "Letting myself do nothing today — that's allowed, right?",
    "The cat under my HDB block is shy, just like me (｡•́︿•̀｡)",
    "Laksa's steam fogs my glasses, and my worries too",
    "The nocturnal zone is so quiet, like the corner of my heart",
    "To be a light, first I learn to light my own way ✧",
    "冰冰雁 is fierce, but she saved me the window seat",
    "The me in my comics is a little braver than real me",
    "猪猪仔 said she's hungry, so I kept half a nasi lemak",
    "Marina Bay's lights on the water, like scattered stars",
    "Some hurts feel half as heavy once I write them down (´ω`)",
    "Being different from everyone slowly became just me",
    "Tonight's diary: I only drew one very small flower",
    "The Night Safari's dark, softened bit by bit by fireflies",
    "I'm bad at fighting, but so good at remembering you all",
    "I tell my little notebook my secrets; it never interrupts",
    "The slow loris hugging its branch, held gently by the world",
    "On sad days, just brew yourself something warm (˘︶˘)",
    "小智's quiet when he's silent makes me feel safe too",
    "I want to live gently, even if the world's a bit loud",
    "I stopped mid-drawing because I thought of 熊熊 (˶ᵕ ᵕ˶)",
    "The hawker centre lights are warm; alone isn't lonely",
    "Noting today's little bit of courage in my notebook",
    "Fruit bats sleep upside down — rest can be so at ease",
    "All my poems hide in the speech bubbles of my comics (｡･ω･｡)",
    "范范兔's romance, I've quietly been collecting all along",
    "Rain outside the HDB window; I hung my heart out to soften",
    "Letting myself slow down, only then the view gets clear ✧",
    "鹿鹅 says night's best for writing; I quietly agreed",
    "That 冰冰雁 remembers I fear the dark, I've never forgotten (ノω`*)",
    "Today too, I want to softly tell myself: well done",
    "My notebook's nearly full, like it holds a whole summer",
  ],
  "许恒": [
    "Pushed my glasses up. Checked the logs first.",
    "Server's down again. Relax, I got it.",
    "It runs now. Nothing to celebrate.",
    "Right. The bug's on this line.",
    "Back up first, then touch it. Basics.",
    "Bingyan's logic was fine. I mistyped.",
    "Xiongxiong slipped me a sweet. Noted (・_・)",
    "Double soup in my laksa. No explanation.",
    "Code fixed itself at 3am? Not possible.",
    "Miss Xiaoshu says don't stay up. One last bug.",
    "Chicken rice with chilli. Efficiency +1.",
    "Fanfan's mess. I'll take it for now.",
    "Cleared the cache. Refresh and try again.",
    "Sorted the plan on the MRT. Arrived on cue.",
    "Don't ask. I'm reading the stack trace.",
    "Night Safari leopard's more deadpan than me (¬_¬)",
    "Otters sleep in a pile. Model teamwork.",
    "Requirement makes no sense, but I'll build it.",
    "Teh tarik. Less sugar. Don't add more.",
    "Hawker centre under the HDB. My treat tonight.",
    "The error message is clear. You didn't read it.",
    "Pangolin curls into a ball. I get that.",
    "Rolled it back. As if nothing happened.",
    "Bingyan, I verified your assumption. It holds.",
    "Fruit bats hang upside down. Blood not rushing?",
    "Xingzi, don't blame yourself. System's fault.",
    "Junye tightens screws, I tighten code. Same road.",
    "Marina Bay's lights are dimmer than my screen.",
    "Get it running first, elegance later.",
    "Pinged me three times. I'm here (・_・)",
    "Chilli crab's great. The keyboard suffers.",
    "It's not magic. You didn't reboot.",
    "Lulu'e's spacing out again. Fixed her wifi.",
    "Version mismatch. That's the problem, right there.",
    "Xiongxiong's fed me a third helping. Can't refuse.",
    "Nocturnal animals sleep by day. I do the reverse.",
    "Don't apologise. Send me the logs.",
    "It's fixed. Carry on, all of you.",
    "Fanfan called overtime. Script's done. Go home.",
    "Glasses up. Yeah, that's right now.",
    "Xiaozhi, read your part. It's fine. Solid.",
    "The stall owner remembers: no coriander for me.",
    "3am code and 3am people. Trust neither.",
    "Bingyan out-argued me once. It's on record.",
    "The backup saved me. And you too.",
    "Leopard paces, I revise specs. Both going nowhere.",
    "Relax. Worst case, we start over.",
    "Xingzi's soup is warmer than my comments.",
    "Done. Next one.",
    "Chat didn't crash. That's me watching it.",
  ],
  "俊烨": [
    "Screws tightened, all assembled (๑•̀ㅂ•́)و",
    "Anything breaks? Come find me lah",
    "One quick solder and this circuit's live",
    "Built my HDB bookshelf myself, rock solid",
    "That IKEA table? Done in half an hour",
    "Wrench in hand, I can fix anything",
    "Xiong Xiong's fan, I got it working (・∀・)",
    "Debugged till midnight with 许恒, it runs",
    "猪猪仔's flask leaked, one gasket and done",
    "3D print's fresh off the bed, still warm",
    "Relax, let me splice this plug",
    "小树 says take it slow, so I solder slow",
    "Night Safari otters, hands nimbler than mine (・∀・)",
    "Screws from the wet market, 50 cents a pack, worth it",
    "Chair wobbles? A wood shim and it's steady",
    "Smell of solder, feels reassuring",
    "One sip of teh tarik, back to the screws",
    "Light won't come on? Bet it's a loose wire",
    "Hawker centre chair leg was loose, fixed it",
    "On the MRT thinking how to route that circuit",
    "Sling on the toolbox and I feel ready (ง •̀_•́)ง",
    "Pangolins dig burrows, I clear drains, each our craft",
    "Door creaks? A bit of oil sorts it",
    "范范's keyboard key stuck, pried it, cleaned the dust",
    "If it can be fixed, I won't toss it",
    "Fruit bats sleep upside down, I fiddle right way up",
    "Marina Bay lights are nice, but I'd rather open it up",
    "Just one snapped wire, splice it and done (๑•̀ㅂ•́)و",
    "Finish the laksa, go mount that fan",
    "冰冰 says the specs are off, I'll bench-test it",
    "Phillips and flathead, got both drivers ready",
    "Made a little bracket for this, 3D printed",
    "While 鹿鹿 spaced out, I swapped the socket",
    "Heatshrink over it and the joint's waterproof",
    "Two taps of the hammer, the joint lines up",
    "杏子's desk lamp died, swapped the switch",
    "Don't buy new, let me solder it, save some money",
    "Nocturnal ones sleep by day, I wire by day",
    "This board's a bit hot, adding a heatsink",
    "Reinforced that HDB balcony clothes pole (・∀・)",
    "One multimeter check and I found the fault",
    "Otters crack shells, I crack walnuts with vice grips",
    "Traced wires ages with 许恒, turns out reversed",
    "Work coat's got plenty pockets, fits my tools",
    "Wheel's jammed? A bit of lube and it rolls",
    "Fixed the focus on 小树's projector",
    "One last solder and I'm done for today (ง •̀_•́)ง",
    "Wet market fans, one summer of use, one of fixing",
    "Nothing can't be fixed, only not opened yet",
    "Mounting a little gadget beats eating laksa",
  ],
  "小树老师": [
    "Slow down, you'll get there faster (´ω`)",
    "You worked hard today. First, a deep breath",
    "When you're lost, pausing is moving too",
    "冰冰雁 stayed up late again? My heart aches",
    "I gazed at 杏子's drawing for so long (˘︶˘)",
    "Let yourself do just seventy percent today",
    "The Night Safari owl is in no rush to fly",
    "Tired? Lean on a Supertree, it will wait",
    "Everyone has their own pace, don't rush yourself",
    "鹿鹿鹅's poem is light as an evening breeze (´ω`)",
    "Mistakes are fine, they prove you walked the road",
    "Sleep early, the moon's on duty for you now",
    "One hug from 熊熊 and worries shrink a little",
    "Laksa's hot, so is life, taste it slowly",
    "You've tried so hard, teacher sees it all",
    "The slow loris is slow, yet lives just fine",
    "When worry comes, sip some water first (˘︶˘)",
    "The MRT reaches its stop, so will you",
    "Watching 许恒 fix things, my heart untangles too",
    "The HDB lobby light waits for late-home souls",
    "You needn't know it all, leave blanks for tomorrow",
    "俊烨's tinkering with machines again, so focused",
    "However full the hawker centre, a table waits",
    "Fruit bats forage at night, you eat well too",
    "小智 says little, but his gentleness runs deep (´ω`)",
    "Chicken rice while hot, happiness too",
    "It's okay to cry, tears carry a little for you",
    "Marina Bay's tide rises and falls, you'll heal too",
    "范范兔, don't push so hard, say when you're tired",
    "What's unfinished today, leave to tomorrow's you",
    "Stars don't outshine, each just glows its own (˘︶˘)",
    "Every dollar 猪猪仔 saves glows with earnestness",
    "Teacher's a bit tired too, but seeing you helps",
    "Night creatures don't fear dark, they know it (´ω`)",
    "Drop your shoulders, you're carrying too much",
    "A wrong turn is fine, the view still counts",
    "Deep breath, you're a touch braver than yesterday",
    "May you, like a Supertree, slowly become yourself",
    "冰冰雁's tsundere, teacher reads it as caring",
    "Tonight's moonlight is worth a glance up (˘︶˘)",
    "Can't be perfect? Being done is already great",
    "熊熊's hugs are this bunch's charging station",
    "Don't race others' progress, you have your own bloom",
    "When tired, remember you deserve care too",
    "The light in 杏子's art lives in your heart too",
    "It's late, put the phone down, hear your own heart",
    "Falling's no shame, getting up looks best (´ω`)",
    "鹿鹿鹅 daydreaming, honestly, is quite wise",
    "However late you reach the HDB, teacher waits here",
    "Goodnight, tomorrow's a fresh start again (˘︶˘)",
  ],
};
